name: Nooku

description: A solid, modern framework and lean architecture for building Joomla extensions.
main_title: Nooku - Joomla Extension Framework
url: http://www.nooku.org

monthly_archive:
  layout: archive
  path: blog

permalink: "/blog/:year/:month/:title"
paginate: 4
paginate_path: "blog/page:num"

# Gems
gems:
  - jekyll-sitemap

# collections
collections:
- events

# We don't want to publish some files
exclude: [
'CNAME',
'Gemfile',
'Gemfile.lock',
'README.md',
'node_modules',
'gruntfile.js',
'package.json',
'scripts'
]
